Repository wisdeom/actiondemo, pull requests merged in 2020-09, with the labels that each got.

#11 label test
  README.md
Labels: approved

#12 Add pr create
  .github/workflows/pr-created.yml
Labels: approved

#14 Tagging test
  README.md
Labels: approved

#15 Delete pr-created.yml
  .github/workflows/pr-created.yml
Labels: approved

#16 Add label commenter
  .github/label-commenter-config.yml
  .github/workflows/label-commenter.yml
Labels: approved

#21 add a custom label
  .github/label-commenter-config.yml
Labels: approved, wisdeom

#23 Update awaiting-review.yml
  .github/workflows/awaiting-review.yml
Labels: awaiting review
